server:
  port: ${SERVER_PORT:8095}

spring:
  application:
    name: edgecloud-api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://EDGECLOUD-AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=3

            - id: monitoring-service
              uri: lb://EDGECLOUD-MONITORING-SERVICE
              predicates:
                - Path=/api/v1/monitoring/**
              filters:
                - StripPrefix=3

            - id: device-service
              uri: lb://EDGECLOUD-DEVICE-SERVICE
              predicates:
                - Path=/api/v1/devices/**
              filters:
                - StripPrefix=3

            - id: alert-service
              uri: lb://EDGECLOUD-ALERT-SERVICE
              predicates:
                - Path=/api/v1/alerts/**
              filters:
                - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

  health:
    defaults:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.edgecloud.gateway: DEBUG
